version: '3.7'

services:
    slack:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tester
        env_file: .env
        environment:
            NODE_ENV: production
        extra_hosts:
          - "host.docker.internal:host-gateway"
